### ISSUE TITLE
Implement the LLL algorithm

### ISSUE THREAD

**Issue by ValarDragon** [pwang00/Gram-Schmidt#1]
Just writing this as a note to you, since you may enjoy implementing it. The LLL algorithm isn't _too_  bad. If I remember correctly Oded Regev provides a good introduction to it somewhere in this talk (I think that part starts after the 1 hr mark): https://www.youtube.com/watch?v=4ulHOV8iLls&list=PL149BD5341FDF6641 

The talk also provides an explanation of a related theorem by Minkowski. Feel free to close the issue you if your not interested though!

Wikipedia also has a nice worked through example, for the un-optimized implementation: https://en.wikipedia.org/wiki/Lenstra%E2%80%93Lenstra%E2%80%93Lov%C3%A1sz_lattice_basis_reduction_algorithm

**Comment by pwang00** [comment]
Thanks!  I'll definitely look into it now that you've mentioned it, and hope to get cracking on it soon.

**Comment by pwang00** [comment]
Done :^^^^^^^^^^^)
